#!/bin/sh
# Copyright 2014 The Rust Project Developers. See the COPYRIGHT
# file at the top-level directory of this distribution and at
# http://rust-lang.org/COPYRIGHT.
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.


msg() {
    echo "rustup: $1"
}

err() {
    echo "rustup: error: $1"
    exit 1
}

CFG_CURL=curl
REMOTE_SCRIPT="https://static.rust-lang.org/rustup.sh"
LOCAL_SCRIPT="/home/a_m0d/workspace/rust/rust-nightly/rustup.sh"

msg "downloading install script"
"${CFG_CURL}" "${REMOTE_SCRIPT}" > "${LOCAL_SCRIPT}"
if [ $? -ne 0 ]
then
	err "failed to download installer"
fi

chmod +x "${LOCAL_SCRIPT}"

sh "${LOCAL_SCRIPT}" --prefix=/home/a_m0d/workspace/rust/rust-nightly
